MORE_SOURCE += ../../../utility-library/search-path/open-sdif-file.c
MORE_SOURCE += ../../../../sdif/lib/sdif-buf.c
MORE_SOURCE += ../../../../sdif/lib/sdif-mem.c
MORE_SOURCE += ../../../../sdif/lib/sdif.c
include ../../../makefile.per-object
