#MORE_JAVAC_OPTIONS += -classpath "../lib/max.jar"
MORE_RELEASE_FILES += ../../../sdif/util/merge-sdif
MORE_RELEASE_FILES += ../../../sdif/util/spew-sdif
MORE_RELEASE_FILES += ../../../sdif/util/change-streamID
MORE_RELEASE_FILES += ../../../sdif/util/streamlist

include ../../makefile.per-javaobject 