MORE_SOURCE += ../../../../sdif/lib/sdif-buf.c
MORE_SOURCE += ../../../../sdif/lib/sdif-mem.c
MORE_SOURCE += ../../../../sdif/lib/sdif.c
# And for SDIF-buffer.h
CFLAGS += -I../SDIF-buffer
include ../../../makefile.per-object
